export const KNOWN_SYSTEMS = [
  // Cost = baseCost + (perBed * bed_count). Sources: KLAS 2025, Becker's, EHR Guides
  { label: "Epic", baseCost: 1500000, perBed: 7500, type: "EHR", cat: "enterprise" },
  { label: "Oracle Health (Cerner) Millennium", baseCost: 1000000, perBed: 5000, type: "EHR", cat: "enterprise" },
  { label: "MEDITECH Expanse", baseCost: 400000, perBed: 1800, type: "EHR", cat: "enterprise" },
  { label: "MEDITECH Magic / Client-Server", baseCost: 250000, perBed: 900, type: "Legacy EHR", cat: "enterprise" },
  { label: "Altera (Allscripts) Sunrise", baseCost: 600000, perBed: 2300, type: "EHR", cat: "enterprise" },
  { label: "Altera Paragon / Denali", baseCost: 400000, perBed: 1300, type: "EHR", cat: "enterprise" },
  { label: "TruBridge (CPSI/Evident)", baseCost: 200000, perBed: 650, type: "EHR", cat: "enterprise" },
  { label: "MEDHOST", baseCost: 150000, perBed: 400, type: "EHR", cat: "enterprise" },
  { label: "Azalea Health", baseCost: 100000, perBed: 250, type: "EHR", cat: "enterprise" },
  { label: "Siemens Soarian", baseCost: 500000, perBed: 2100, type: "Legacy EHR", cat: "enterprise" },
  { label: "GE Centricity", baseCost: 350000, perBed: 1400, type: "Legacy EHR", cat: "enterprise" },
  { label: "McKesson Paragon", baseCost: 300000, perBed: 1100, type: "Legacy EHR", cat: "enterprise" },
  { label: "eClinicalWorks", baseCost: 150000, perBed: 320, type: "Ambulatory EHR", cat: "departmental" },
  { label: "athenahealth", baseCost: 200000, perBed: 480, type: "Ambulatory EHR/RCM", cat: "departmental" },
  { label: "NextGen Healthcare", baseCost: 120000, perBed: 280, type: "Ambulatory EHR", cat: "departmental" },
  { label: "Greenway Health", baseCost: 100000, perBed: 240, type: "Ambulatory EHR", cat: "departmental" },
  { label: "Veradigm (Allscripts Practice)", baseCost: 80000, perBed: 190, type: "Ambulatory EHR", cat: "departmental" },
  { label: "Varian ARIA", baseCost: 1200000, perBed: 2800, type: "Oncology", cat: "departmental" },
  { label: "Netsmart", baseCost: 150000, perBed: 400, type: "Behavioral Health", cat: "departmental" },
  { label: "WellSky", baseCost: 120000, perBed: 360, type: "Post-Acute/Rehab", cat: "departmental" },
  { label: "Philips ICCA / Capsule", baseCost: 200000, perBed: 480, type: "ICU/Critical Care", cat: "departmental" },
  { label: "Cerner Soarian Financials", baseCost: 300000, perBed: 800, type: "Revenue Cycle", cat: "departmental" },
  { label: "GE Centricity Perinatal", baseCost: 120000, perBed: 280, type: "OB/Perinatal", cat: "departmental" },
  { label: "Nuance PowerScribe / DAX", baseCost: 200000, perBed: 620, type: "Clinical Documentation", cat: "standalone" },
  { label: "3M / Solventum CDI", baseCost: 150000, perBed: 400, type: "CDI/Coding", cat: "standalone" },
  { label: "Omnicell / Pyxis", baseCost: 300000, perBed: 800, type: "Pharmacy/Dispensing", cat: "standalone" },
  { label: "Hyland OnBase", baseCost: 120000, perBed: 360, type: "Document Management", cat: "standalone" },
  { label: "InterSystems TrakCare", baseCost: 500000, perBed: 1600, type: "EHR/Integration", cat: "enterprise" },
  { label: "Rhapsody / Corepoint", baseCost: 80000, perBed: 190, type: "Integration Engine", cat: "standalone" },
  // Additional standalone systems common in US hospitals
  { label: "Hyland NilRead", baseCost: 60000, perBed: 150, type: "Document Management", cat: "standalone" },
  { label: "LaserFiche", baseCost: 50000, perBed: 120, type: "Document Management", cat: "standalone" },
  { label: "OpenText", baseCost: 80000, perBed: 200, type: "Document Management", cat: "standalone" },
  { label: "MModal Fluency / 3M", baseCost: 100000, perBed: 300, type: "Dictation/Transcription", cat: "standalone" },
  { label: "Dragon Medical (legacy)", baseCost: 60000, perBed: 180, type: "Dictation/Transcription", cat: "standalone" },
  { label: "Sunquest Lab", baseCost: 200000, perBed: 500, type: "Laboratory", cat: "standalone" },
  { label: "Orchard Harvest LIS", baseCost: 80000, perBed: 220, type: "Laboratory", cat: "standalone" },
  { label: "GE Centricity PACS (legacy)", baseCost: 150000, perBed: 380, type: "Legacy PACS", cat: "standalone" },
  { label: "Fujifilm Synapse PACS", baseCost: 180000, perBed: 420, type: "Legacy PACS", cat: "standalone" },
  { label: "Vocera / Stryker", baseCost: 70000, perBed: 180, type: "Clinical Communication", cat: "standalone" },
  { label: "TigerConnect", baseCost: 50000, perBed: 120, type: "Clinical Communication", cat: "standalone" },
  { label: "RL Solutions (Datix)", baseCost: 60000, perBed: 150, type: "Incident/Risk", cat: "standalone" },
  { label: "Theradoc (ICNet)", baseCost: 80000, perBed: 200, type: "Infection Control", cat: "standalone" },
  { label: "Kronos / UKG", baseCost: 100000, perBed: 250, type: "Workforce/Scheduling", cat: "standalone" },
  { label: "QGenda", baseCost: 60000, perBed: 140, type: "Workforce/Scheduling", cat: "standalone" },
  { label: "Dimensional Insight", baseCost: 80000, perBed: 200, type: "Data Warehouse", cat: "standalone" },
  { label: "IBM Cognos (legacy)", baseCost: 90000, perBed: 220, type: "Data Warehouse", cat: "standalone" },
]
export function systemCost(sys, beds) { return Math.round(((sys.baseCost || 250000) + (sys.perBed || 0) * beds) / 1000) * 1000; }
